apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: staging-helm-guestbook
  name: staging-helm-guestbook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: staging-helm-guestbook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: staging-helm-guestbook
  name: staging-helm-guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: staging-helm-guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: staging-helm-guestbook
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: argocd-health
spec:
  applicationSelector:
    matchLabels:
      app-name: helm-guestbook
  promotionStrategyRef:
    name: demo-github
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: github-argocd-example-apps
spec:
  github:
    name: argocd-example-apps
    owner: cNorspang
  scmProviderRef:
    name: github
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo-github
spec:
  activeCommitStatuses:
    - key: argocd-health
  environments:
    - autoMerge: true
      branch: environment/development
    - autoMerge: true
      branch: environment/staging
    - autoMerge: false
      branch: environment/prod
  gitRepositoryRef:
    name: github-argocd-example-apps
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  name: github
spec:
  github:
    appID: 3617473
  secretRef:
    name: github-app-promoter
