apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: github-argocd-example-apps
spec:
  github:
    owner: cNorspang
    name: argocd-example-apps
  scmProviderRef:
    name: github
