apiVersion: promoter.argoproj.io/v1alpha1
kind: ClusterScmProvider
metadata:
  name: github
spec:
  github:
    appID: 3617473
  secretRef:
    name: github-app-promoter
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: github-argocd-example-apps
  namespace: argocd
spec:
  github:
    name: argocd-example-apps
    owner: cNorspang
  scmProviderRef:
    kind: ClusterScmProvider
    name: github
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo-github
  namespace: argocd
spec:
  activeCommitStatuses:
    - key: argocd-health
  environments:
    - autoMerge: true
      branch: environment/development
    - autoMerge: true
      branch: environment/staging
    - autoMerge: false
      branch: environment/prod
  gitRepositoryRef:
    name: github-argocd-example-apps
